### ISSUE TITLE
multiple event recordings

### ISSUE THREAD

**Issue by walleser** [walleser/dairy-comp#5]
Many dairies will record the same event on successive days. We need to account for multiple event recordings. This varies by disease. 

See example below for DA event. Some issues will be recorded close together. Ketosis is frequently diagnosed within 3 day period. DA would be considered as one event over the same time period.

Example in toy dataset:

ID | LACT | FDAT | BDAT | FCDAT | RC | DRYLG | DDRY | PDCC | PDIM | EASE | CNUM | CLIVE | CSEX | FTDIM | FSTPJ | FSTBF | FSTPR | PEAKM | DCAR | PR305 | LOG1 | Event | DIM | Date | Remark | R | T | B | Protocols | Technician
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
4700 | 3 | 3/13/2021 | 3/5/2017 | 12/12/2018 | 6 | 6.5 | 54 | 282 | 306 | 1 | 1 | A | F | 25 | 31070 | 5 | 2.6 | 139 | 0 | 36600 | 7.4 | DA | 30 | 4/12/2021 | KETOSIS |   |   |   |   |   |  
4700 | 3 | 3/13/2021 | 3/5/2017 | 12/12/2018 | 6 | 6.5 | 54 | 282 | 306 | 1 | 1 | A | F | 25 | 31070 | 5 | 2.6 | 139 | 0 | 36600 | 7.4 | DA | 30 | 4/12/2021 | EXC24 |   |   |   |   |   |  
5657 | 1 | 11/7/2021 | 12/26/2019 | 11/7/2021 | 6 | 3.4 | 0 | 276 | 0 | 1 | 1 | A | M | 24 | 25080 | 3.5 | 2.6 | 96 | 0 | 0 | 1.7 | DA | 187 | 5/13/2022 | PO22.5/3 |   |   |   |   |   |  
5657 | 1 | 11/7/2021 | 12/26/2019 | 11/7/2021 | 6 | 3.4 | 0 | 276 | 0 | 1 | 1 | A | M | 24 | 25080 | 3.5 | 2.6 | 96 | 0 | 0 | 1.7 | DA | 187 | 5/13/2022 | HEAT? |   |   |   |   |   |

**Comment by aravamu2** [comment]
```
f <- function(prev, curr, roll = 3) {
  if_else(as.numeric(curr - prev) > roll, curr, prev) %>%
    lubridate::as_date()
}

df %>% 
  select(ID, LACT, Date, Event) %>%
  mutate_if(is.numeric, as.character) %>% 
  mutate(Date = lubridate::mdy(Date)) %>% 
  group_by(ID, LACT, Event) %>% 
  # filter(n() > 1) %>%
  arrange(ID, LACT, Event, Date) %>% 
  mutate(
    x = Date,
    x = purrr::accumulate(x, f) %>% 
      lubridate::as_date()
  ) %>% 
  distinct(ID, LACT, Event, x)
  # filter(lag(x, default = as_date(0)) != x)
```

**Comment by aravamu2** [comment]
```
tibble(
  ID = 1,
  LACT = 1,
  Date = c(seq(ymd('2022-10-25'),ymd('2022-10-31'), by = 'day'), 
           seq(ymd('2022-11-01'),ymd('2022-11-07'), by = '2 days'),
           seq(ymd('2022-11-08'),ymd('2022-11-14'), by = '3 days'),
           seq(ymd('2022-11-15'),ymd('2022-11-21'), by = '4 days')),
  Event = "MAST"
) %>% 
  group_by(ID, LACT, Event) %>% 
  # filter(n() > 1) %>%
  arrange(ID, LACT, Event, Date) %>% 
  mutate(
    x = Date,
    x = purrr::accumulate(x, f) %>% 
      lubridate::as_date()
  ) %>% 
  distinct(ID, LACT, Event, x)
  # filter(lag(x, default = as_date(0)) != x)
```

**Comment by aravamu2** [comment]
> ```
> tibble(
>   ID = 1,
>   LACT = 1,
>   Date = c(seq(ymd('2022-10-25'),ymd('2022-10-31'), by = 'day'), 
>            seq(ymd('2022-11-01'),ymd('2022-11-07'), by = '2 days'),
>            seq(ymd('2022-11-08'),ymd('2022-11-14'), by = '3 days'),
>            seq(ymd('2022-11-15'),ymd('2022-11-21'), by = '4 days')),
>   Event = "MAST"
> ) %>% 
>   group_by(ID, LACT, Event) %>% 
>   # filter(n() > 1) %>%
>   arrange(ID, LACT, Event, Date) %>% 
>   mutate(
>     x = Date,
>     x = purrr::accumulate(x, f) %>% 
>       lubridate::as_date()
>   ) %>% 
>   distinct(ID, LACT, Event, x)
>   # filter(lag(x, default = as_date(0)) != x)
> ```

ID | LACT | Event | x
-- | -- | -- | -- 
1 | 1 | MAST | 2022-10-25
1 | 1 | MAST | 2022-10-29
1 | 1 | MAST | 2022-11-03
1 | 1 | MAST | 2022-11-07
1 | 1 | MAST | 2022-11-11
1 | 1 | MAST | 2022-11-15
1 | 1 | MAST | 2022-11-19

**Comment by aravamu2** [comment]
@walleser default lag time (roll)? currently set to 3 days.

**Comment by walleser** [comment]
A default lag time of 3 days makes sense, I will continue to evaluate for issues during testing phase
