### ISSUE TITLE
dashboard tab contents box previews only 6 rows 

### ISSUE THREAD

**Issue by walleser** [walleser/dairy-comp#6]
dataset: wall_testdata_10_12_22.csv
issue: preview only 6 rows.

**Comment by aravamu2** [comment]
used `head` to preview the first `n` rows. defaults to ` n = 6`.

**Comment by walleser** [comment]
changing the dropdown box to other options does not increase the number of visible rows

**Comment by aravamu2** [comment]
```
  output$contents <- 
    DT::renderDataTable(
      {
        head(df(), n = 100)
      }, 
      options = list(scrollX = TRUE)
    )
```
