### ISSUE TITLE
pivot table odds ratio & forest plot do not display correctly

### ISSUE THREAD

**Issue by walleser** [walleser/dairy-comp#8]
dataset: wall_testdata_10_12_22.csv
issue: Odds Ratio and Forest plot give error warnings for Row variables LCTGP, CALVING_EASE_>=2

notes:

- pivot table and barplot display correctly
- all cells have greater than 20 observations

**Comment by aravamu2** [comment]
@aravamu2 fit model via multinomial regression using wall_testdata_10_12_22.csv

**Comment by aravamu2** [comment]
#33 add tick marks around column names for formula
